# Generated by Selenium IDE
# Modified by farrrrland
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    options=webdriver.ChromeOptions()
    options.add_argument('--disable-web-security')
    self.driver = webdriver.Chrome(chrome_options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1054, 848)
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").send_keys("鱼")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button > .el-icon-search").click()
    self.driver.implicitly_wait(100)
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").send_keys("鳕鱼")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button > .el-icon-search").click()
    self.driver.implicitly_wait(100)
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").send_keys("item")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--box:nth-child(2) > span").click()
    self.driver.implicitly_wait(100)
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").send_keys("啥也不是")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--box:nth-child(2) > span").click()
    self.driver.close()
  
if __name__ == '__main__':
    pytest.main()